import { currencyColumn, dateColumn, linkColumn, nestedNameColumn, statusColumn } from "../columns";
import type { ResourceDef } from "../types";

const basePath = "/dashboard/disbursements";

export const disbursementResource: ResourceDef = {
  resource: "/disbursements",
  basePath,
  label: "Pengeluaran",
  labelPlural: "Pengeluaran",
  permissions: {
    view: "disbursement.view",
    create: "disbursement.create",
  },
  titleField: (row) => String(row.disbursement_number ?? `Pengeluaran #${row.id}`),
  listColumns: [
    linkColumn("disbursement_number", "No. Pengeluaran", basePath, (row) =>
      String(row.disbursement_number ?? `#${row.id}`),
    ),
    dateColumn("disbursement_date", "Tanggal"),
    currencyColumn("amount", "Nominal"),
    statusColumn(),
    nestedNameColumn("account", "Akun"),
    { accessorKey: "payee", header: "Penerima" },
  ],
  filters: [
    {
      name: "status",
      label: "Status",
      type: "select",
      allLabel: "Semua status",
      options: [
        { value: "draft", label: "Draft" },
        { value: "submitted", label: "Submitted" },
        { value: "verified", label: "Verified" },
        { value: "approved", label: "Approved" },
        { value: "rejected", label: "Rejected" },
        { value: "reversed", label: "Reversed" },
      ],
    },
  ],
  defaultSort: { field: "disbursement_date", direction: "desc" },
  formFields: [
    { name: "disbursement_date", label: "Tanggal Pengeluaran", type: "date", required: true },
    {
      name: "account_id",
      label: "Akun Kas/Bank",
      type: "relation",
      required: true,
      relation: { resource: "/accounts", labelKey: "name", params: { is_active: 1, per_page: 100 } },
    },
    {
      name: "program_id",
      label: "Program",
      type: "relation",
      relation: { resource: "/programs", labelKey: "name", params: { is_active: 1, per_page: 100 } },
    },
    { name: "amount", label: "Nominal", type: "currency", required: true },
    { name: "payee", label: "Penerima", type: "text" },
    { name: "category", label: "Kategori", type: "text" },
    { name: "reference_number", label: "No. Referensi", type: "text" },
    { name: "description", label: "Keterangan", type: "textarea" },
  ],
  lineItems: {
    key: "sources",
    label: "Sumber Dana",
    amountField: "amount",
  },
  detailFields: [
    { label: "No. Pengeluaran", accessor: "disbursement_number" },
    { label: "Tanggal", accessor: "disbursement_date", type: "date" },
    { label: "Status", accessor: "status", type: "status" },
    { label: "Nominal", accessor: "amount", type: "currency" },
    { label: "Akun", accessor: (row) => (row.account as { name?: string } | undefined)?.name ?? "-" },
    { label: "Program", accessor: (row) => (row.program as { name?: string } | undefined)?.name ?? "-" },
    { label: "Penerima", accessor: "payee" },
    { label: "Kategori", accessor: "category" },
    { label: "No. Referensi", accessor: "reference_number" },
    { label: "Keterangan", accessor: "description" },
    { label: "Alasan Penolakan", accessor: "rejection_reason" },
    { label: "Alasan Reversal", accessor: "reversal_reason" },
    { label: "Dibuat", accessor: "created_at", type: "datetime" },
  ],
  workflow: [
    {
      action: "submit",
      label: "Submit",
      permission: "disbursement.submit",
      statuses: ["draft"],
      confirmTitle: "Submit pengeluaran?",
    },
    {
      action: "verify",
      label: "Verifikasi",
      permission: "disbursement.verify",
      statuses: ["submitted"],
      notesOptional: true,
      confirmTitle: "Verifikasi pengeluaran?",
    },
    {
      action: "approve",
      label: "Setujui",
      permission: "disbursement.approve",
      statuses: ["verified"],
      notesOptional: true,
      confirmTitle: "Setujui pengeluaran?",
      confirmDescription: "Transaksi akan diposting ke buku besar.",
    },
    {
      action: "reject",
      label: "Tolak",
      permission: "disbursement.reject",
      statuses: ["submitted", "verified"],
      requiresReason: true,
      reasonLabel: "Alasan penolakan",
      reasonRequired: true,
      variant: "destructive",
      confirmTitle: "Tolak pengeluaran?",
    },
    {
      action: "reverse",
      label: "Reverse",
      permission: "disbursement.reverse",
      statuses: ["approved"],
      requiresReason: true,
      reasonLabel: "Alasan reversal",
      reasonRequired: true,
      variant: "destructive",
      confirmTitle: "Reverse pengeluaran?",
    },
  ],
  attachments: {
    attachableType: "disbursement",
    managePermission: "attachment.manage",
  },
  audit: {
    auditableType: "App\\Models\\Disbursement",
    permission: "audit.view",
  },
  getCreateDefaults: () => ({
    disbursement_date: new Date().toISOString().slice(0, 10),
    amount: "",
    sources: [{ fund_id: "", program_id: "", amount: "", note: "" }],
  }),
  mapToForm: (row) => ({
    disbursement_date: row.disbursement_date,
    account_id: row.account_id ? String(row.account_id) : "",
    program_id: row.program_id ? String(row.program_id) : "",
    amount: row.amount ?? "",
    payee: row.payee ?? "",
    category: row.category ?? "",
    reference_number: row.reference_number ?? "",
    description: row.description ?? "",
    sources: ((row.fund_sources as Array<Record<string, unknown>> | undefined) ?? []).map((line) => ({
      fund_id: line.fund_id ? String(line.fund_id) : "",
      program_id: line.program_id ? String(line.program_id) : "",
      amount: line.amount ?? "",
      note: line.note ?? "",
    })),
  }),
  mapToPayload: (values) => ({
    disbursement_date: values.disbursement_date,
    account_id: Number(values.account_id),
    program_id: values.program_id ? Number(values.program_id) : null,
    amount: values.amount,
    payee: values.payee || null,
    category: values.category || null,
    reference_number: values.reference_number || null,
    description: values.description || null,
    sources: (values.sources as Array<Record<string, unknown>>).map((line) => ({
      fund_id: Number(line.fund_id),
      program_id: line.program_id ? Number(line.program_id) : null,
      amount: line.amount,
      note: line.note || null,
    })),
  }),
  canEdit: (row) => row.status === "draft",
  canDelete: () => false,
};
