import { amountToMoneyInput, normalizeAmountString } from "@/lib/format/amount";

import { currencyColumn, dateColumn, linkColumn, nestedNameColumn, statusColumn } from "../columns";
import type { ResourceDef } from "../types";

const basePath = "/dashboard/receipts";

export const receiptResource: ResourceDef = {
  resource: "/receipts",
  basePath,
  label: "Penerimaan",
  labelPlural: "Penerimaan",
  permissions: {
    view: "receipt.view",
    create: "receipt.create",
  },
  titleField: (row) => String(row.receipt_number ?? `Penerimaan #${row.id}`),
  listColumns: [
    linkColumn("receipt_number", "No. Penerimaan", basePath, (row) => String(row.receipt_number ?? `#${row.id}`)),
    dateColumn("receipt_date", "Tanggal"),
    currencyColumn("amount", "Nominal"),
    statusColumn(),
    nestedNameColumn("account", "Akun"),
    nestedNameColumn("donor", "Donatur"),
  ],
  filters: [
    {
      name: "status",
      label: "Status",
      type: "select",
      allLabel: "Semua status",
      options: [
        { value: "draft", label: "Draft" },
        { value: "submitted", label: "Submitted" },
        { value: "approved", label: "Approved" },
        { value: "rejected", label: "Rejected" },
        { value: "reversed", label: "Reversed" },
      ],
    },
  ],
  defaultSort: { field: "receipt_date", direction: "desc" },
  formFields: [
    { name: "receipt_date", label: "Tanggal Penerimaan", type: "date", required: true },
    {
      name: "account_id",
      label: "Akun Kas/Bank",
      type: "relation",
      required: true,
      relation: { resource: "/accounts", labelKey: "name", params: { is_active: 1, per_page: 100 } },
    },
    {
      name: "donor_id",
      label: "Donatur",
      type: "relation",
      relation: { resource: "/donors", labelKey: "name", params: { is_active: 1, per_page: 100 } },
    },
    {
      name: "channel",
      label: "Channel",
      type: "select",
      required: true,
      options: [
        { value: "cash", label: "Tunai" },
        { value: "transfer", label: "Transfer" },
        { value: "qris", label: "QRIS" },
        { value: "other", label: "Lainnya" },
      ],
    },
    { name: "reference_number", label: "No. Referensi", type: "text" },
    { name: "amount", label: "Nominal", type: "currency", required: true, placeholder: "0" },
    { name: "description", label: "Keterangan", type: "textarea" },
  ],
  lineItems: {
    key: "allocations",
    label: "Alokasi Dana",
    amountField: "amount",
  },
  detailFields: [
    { label: "No. Penerimaan", accessor: "receipt_number" },
    { label: "Tanggal", accessor: "receipt_date", type: "date" },
    { label: "Status", accessor: "status", type: "status" },
    { label: "Nominal", accessor: "amount", type: "currency" },
    { label: "Akun", accessor: (row) => (row.account as { name?: string } | undefined)?.name ?? "-" },
    { label: "Donatur", accessor: (row) => (row.donor as { name?: string } | undefined)?.name ?? "-" },
    { label: "Channel", accessor: "channel" },
    { label: "No. Referensi", accessor: "reference_number" },
    { label: "Keterangan", accessor: "description" },
    { label: "Alasan Penolakan", accessor: "rejection_reason" },
    { label: "Alasan Reversal", accessor: "reversal_reason" },
    { label: "Dibuat", accessor: "created_at", type: "datetime" },
  ],
  workflow: [
    {
      action: "submit",
      label: "Submit",
      permission: "receipt.submit",
      statuses: ["draft"],
      variant: "default",
      confirmTitle: "Submit penerimaan?",
      confirmDescription: "Penerimaan akan masuk antrian persetujuan.",
    },
    {
      action: "approve",
      label: "Setujui",
      permission: "receipt.approve",
      statuses: ["submitted"],
      notesOptional: true,
      confirmTitle: "Setujui penerimaan?",
      confirmDescription: "Transaksi akan diposting ke buku besar.",
    },
    {
      action: "reject",
      label: "Tolak",
      permission: "receipt.reject",
      statuses: ["submitted"],
      requiresReason: true,
      reasonLabel: "Alasan penolakan",
      reasonRequired: true,
      variant: "destructive",
      confirmTitle: "Tolak penerimaan?",
    },
    {
      action: "reverse",
      label: "Reverse",
      permission: "receipt.reverse",
      statuses: ["approved"],
      requiresReason: true,
      reasonLabel: "Alasan reversal",
      reasonRequired: true,
      variant: "destructive",
      confirmTitle: "Reverse penerimaan?",
    },
  ],
  attachments: {
    attachableType: "receipt",
    managePermission: "attachment.manage",
  },
  audit: {
    auditableType: "App\\Models\\Receipt",
    permission: "audit.view",
  },
  getCreateDefaults: () => ({
    receipt_date: new Date().toISOString().slice(0, 10),
    channel: "transfer",
    amount: "",
    allocations: [{ fund_id: "", program_id: "", amount: "", note: "" }],
  }),
  mapToForm: (row) => ({
    receipt_date: row.receipt_date,
    account_id: row.account_id ? String(row.account_id) : "",
    donor_id: row.donor_id ? String(row.donor_id) : "",
    channel: row.channel,
    reference_number: row.reference_number ?? "",
    amount: amountToMoneyInput(row.amount as string | number | null | undefined),
    description: row.description ?? "",
    allocations: ((row.allocations as Array<Record<string, unknown>> | undefined) ?? []).map((line) => ({
      fund_id: line.fund_id ? String(line.fund_id) : "",
      program_id: line.program_id ? String(line.program_id) : "",
      amount: amountToMoneyInput(line.amount as string | number | null | undefined),
      note: line.note ?? "",
    })),
  }),
  mapToPayload: (values) => ({
    receipt_date: values.receipt_date,
    account_id: Number(values.account_id),
    donor_id: values.donor_id ? Number(values.donor_id) : null,
    channel: values.channel,
    reference_number: values.reference_number || null,
    amount: normalizeAmountString(values.amount as string),
    description: values.description || null,
    allocations: (values.allocations as Array<Record<string, unknown>>).map((line) => ({
      fund_id: Number(line.fund_id),
      program_id: line.program_id ? Number(line.program_id) : null,
      amount: normalizeAmountString(line.amount as string),
      note: line.note || null,
    })),
  }),
  canEdit: (row) => row.status === "draft",
  canDelete: () => false,
};
